# Generated by Django 4.2 on 2024-12-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupervisorCreatetask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("heading", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("days", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SupervisorCreateworker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
                ("heading", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("group", models.CharField(max_length=50)),
                ("days", models.IntegerField()),
            ],
        ),
    ]
