# Generated by Django 4.2 on 2024-12-07 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0004_worker_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="group",
        ),
    ]
