# Generated by Django 5.1.2 on 2024-11-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0004_workers_alter_tasks_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workers",
            old_name="workertype",
            new_name="worktype",
        ),
    ]
