# Generated by Django 5.1.2 on 2024-11-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0005_rename_workertype_workers_worktype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workers",
            name="image",
            field=models.ImageField(upload_to="workerimages/"),
        ),
    ]
