# Generated by Django 5.1.2 on 2024-11-27 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0006_alter_workers_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Farmers",
            new_name="Farmer",
        ),
        migrations.RenameModel(
            old_name="Tasks",
            new_name="Task",
        ),
        migrations.RenameModel(
            old_name="Workers",
            new_name="Worker",
        ),
    ]
