# Generated by Django 5.1.2 on 2024-11-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0007_rename_farmers_farmer_rename_tasks_task_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(max_length=100)),
                ("workId", models.IntegerField()),
                ("subject", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="contactimages/")),
            ],
        ),
    ]
